package com.example.compose
import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF116D34)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFF9FF6AE)
val md_theme_light_onPrimaryContainer = Color(0xFF00210A)
val md_theme_light_secondary = Color(0xFF326B00)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFF8AFE2F)
val md_theme_light_onSecondaryContainer = Color(0xFF0B2000)
val md_theme_light_tertiary = Color(0xFF006689)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFC3E8FF)
val md_theme_light_onTertiaryContainer = Color(0xFF001E2C)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF1B0261)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF1B0261)
val md_theme_light_surfaceVariant = Color(0xFFD7EDCE) //IMPORTANT ELEMENT
val md_theme_light_onSurfaceVariant = Color(0xFF414941)
val md_theme_light_outline = Color(0xFF727970)
val md_theme_light_inverseOnSurface = Color(0xFFF4EEFF)
val md_theme_light_inverseSurface = Color(0xFF302175)
val md_theme_light_inversePrimary = Color(0xFF84D994)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF116D34)
val md_theme_light_outlineVariant = Color(0xFFC1C9BE)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF84D994)
val md_theme_dark_onPrimary = Color(0xFF003917)
val md_theme_dark_primaryContainer = Color(0xFF005224)
val md_theme_dark_onPrimaryContainer = Color(0xFF9FF6AE)
val md_theme_dark_secondary = Color(0xFF6FE000)
val md_theme_dark_onSecondary = Color(0xFF173800)
val md_theme_dark_secondaryContainer = Color(0xFF245100)
val md_theme_dark_onSecondaryContainer = Color(0xFF8AFE2F)
val md_theme_dark_tertiary = Color(0xFF7AD0FF)
val md_theme_dark_onTertiary = Color(0xFF003549)
val md_theme_dark_tertiaryContainer = Color(0xFF004C68)
val md_theme_dark_onTertiaryContainer = Color(0xFFC3E8FF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1B0261)
val md_theme_dark_onBackground = Color(0xFFE5DEFF)
val md_theme_dark_surface = Color(0xFF1B0261)
val md_theme_dark_onSurface = Color(0xFFE5DEFF)
val md_theme_dark_surfaceVariant = Color(0xFF414941)
val md_theme_dark_onSurfaceVariant = Color(0xFFC1C9BE)
val md_theme_dark_outline = Color(0xFF8B9389)
val md_theme_dark_inverseOnSurface = Color(0xFF1B0261)
val md_theme_dark_inverseSurface = Color(0xFFE5DEFF)
val md_theme_dark_inversePrimary = Color(0xFF116D34)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFF84D994)
val md_theme_dark_outlineVariant = Color(0xFF414941)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFFB6FFC0)
